### ISSUE TITLE
On the global batch size of dino contrastive loss

### ISSUE THREAD

**Issue by jiachunjin** [lxa9867/ImageFolder#4]
Hi, thanks for your great work!
It is known that CLIP style contrast loss requires huge global batch sizes (e.g. 32k). I'd like to know if this is a critical issue in your training and the global batch size you use.

**Comment by lxa9867** [comment]
Hi,

Thanks for your interest. It does not require 32k bs to make the clip loss work. In our approach, we notice that a bs larger than 768 can work. 

The final bs we used is 1024. We are not able to try 32k bs due to GPU limitation but we expect that will be beneficial to the knowledge distillation.

**Comment by lxa9867** [comment]
code released, closing this issue.
